package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init [name]",
	Short: "Initialise a new LFRD website project",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		projectName := args[0]

		// make project folder
		if err := os.Mkdir(projectName, 0755); err != nil {
			fmt.Println("Error creating project:", err)
			return
		}

		// create index.html inside
		indexPath := filepath.Join(projectName, "index.html")
		content := `<!DOCTYPE html>
<html>
  <head>
    <title>` + projectName + `</title>
  </head>
  <body>
    <h1>Welcome to ` + projectName + `!</h1>
    <p>Site generated by LFRD 🚀</p>
  </body>
</html>`
		if err := os.WriteFile(indexPath, []byte(content), 0644); err != nil {
			fmt.Println("Error writing index.html:", err)
			return
		}

		fmt.Printf("✅ Project '%s' created successfully!\n", projectName)
	},
}
